# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.version.version

'1.11.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
x = np.zeros(10)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
bytes = x.size * x.itemsize
bytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
x[4] = 1
x

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
y = np.arange(10,50)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [18]:
y = np.arange(50)
print(y)
y[::-1]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [28]:
y = np.array([1,2,0,0,4,0])
y = np.nonzero(y)
y

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
y = np.eye(3)
y

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
y = np.random.random((3,3,3))
y

array([[[ 0.09830103,  0.40111485,  0.39254698],
        [ 0.93056425,  0.95558164,  0.8881077 ],
        [ 0.91478793,  0.26906214,  0.08254937]],

       [[ 0.29802192,  0.47377092,  0.3129644 ],
        [ 0.54997772,  0.57278171,  0.35730855],
        [ 0.96441278,  0.71196746,  0.39603352]],

       [[ 0.62007496,  0.95353193,  0.57911649],
        [ 0.33050681,  0.03245303,  0.74656226],
        [ 0.0875044 ,  0.71662446,  0.42296852]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
y = np.random.random((10,10))
Ymin, Ymax = y.min(), y.max()
print(y)
print(Ymin, Ymax)

[[ 0.46966273  0.41416619  0.85590342  0.34830127  0.79604518  0.6059274
   0.2143549   0.2877214   0.90819729  0.88609581]
 [ 0.20726831  0.73832621  0.42267302  0.44775041  0.4347952   0.68606149
   0.32382233  0.37435158  0.18221747  0.76664017]
 [ 0.05627592  0.93101177  0.25077287  0.5091178   0.54943792  0.52849268
   0.16605248  0.00458811  0.02980945  0.42764203]
 [ 0.97963447  0.56978691  0.32287     0.54604903  0.5757515   0.40218777
   0.59217155  0.55746889  0.61870419  0.8885554 ]
 [ 0.71227501  0.00289922  0.65612339  0.46076024  0.29046031  0.33671135
   0.85831264  0.50594279  0.95987476  0.1598988 ]
 [ 0.533011    0.624005    0.25495215  0.03028912  0.75454455  0.86993544
   0.96518701  0.39448261  0.6437185   0.12002255]
 [ 0.63456188  0.85318301  0.23795891  0.50111658  0.64971812  0.6595042
   0.63713583  0.43144835  0.71920712  0.93336955]
 [ 0.47538817  0.4161046   0.18310277  0.86715601  0.49464871  0.26392949
   0.33531519  0.37249039  0.01859294  0.61283273]
 [

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [33]:
y = np.random.random(30)
mei = y.mean()
print(y)
print(mei)

[ 0.99981573  0.19427869  0.27774067  0.84600233  0.13348189  0.10527229
  0.90703892  0.81975469  0.1714693   0.73166905  0.58608739  0.31656832
  0.04726951  0.64396108  0.56024631  0.40925082  0.08489854  0.64861376
  0.48562323  0.02871327  0.78237173  0.47839553  0.69142518  0.36801517
  0.40183335  0.05509061  0.96834836  0.13950001  0.25720267  0.48863214]
0.454285684052


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [7]:
y = np.ones((6,6))
y[1:-1,1:-1] = 0
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [10]:
y = np.pad(y, pad_width=1, mode='constant', constant_values=0)
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [13]:
c = 0*np.nan
b = np.nan == np.nan
a = np.inf>np.nan
d = np.nan - np.nan
e = 0.3 - 3*0.1
print(a, b, c, d, e)

False False nan nan -5.551115123125783e-17


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
y = np.diag(1+np.arange(4), k=-1)
y

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [15]:
y = np.zeros((8,8),dtype=int)
y[1::2,::2] = 1
y[::2,1::2] = 1
y

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [17]:
y = np.tile( np.array([[0,1],[1,0]]), (4,4))
y

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [18]:
y = np.random.random((5,5))
ymax, ymin = y.max(), y.min()
y = (y - ymin)/(ymax - ymin)
y

array([[0.2255465 , 0.66448112, 0.74860775, 0.52826136, 0.46727473],
       [0.1747849 , 0.62477483, 0.45146116, 0.09821103, 0.72039462],
       [0.35841738, 0.1646576 , 0.        , 0.06680654, 0.48809806],
       [0.0730781 , 0.87698279, 0.46700708, 0.02261856, 0.4363221 ],
       [0.38541932, 0.7741991 , 1.        , 0.79862045, 0.9509021 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [19]:
cor = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
cor

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
y = np.dot(np.ones((5,3)), np.ones((3,2)))
y

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
y = np.arange(11)
y[(3 < y) & (y <= 8)] *= -1
y

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
Z = np.arange(3,5)
a = Z**Z
b = 2 << Z >> 2
c = Z <- Z
d = 1j*Z
e = Z/1/1
#Z<Z>Z não é definida
print(a, b, c, d, e)

[ 27 256] [4 8] [False False] [0.+3.j 0.+4.j] [3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [38]:
y = np.random.uniform(-10,+10,10)
print(y)
print (np.trunc(y + np.copysign(0.5, y)))

[-0.9704172   7.70436063  5.78821369 -8.335162    1.28836052  8.23734267
 -2.28058459 -9.34878377 -3.96307444  7.91676862]
[-1.  8.  6. -8.  1.  8. -2. -9. -4.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [39]:
y1 = np.arange(3,5)
y2 = np.arange(3,5)
a = np.intersect1d(y1, y2)
a

array([3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [44]:
np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [41]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
ontem = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Ontem: ",ontem)
hoje= np.datetime64('today', 'D')
print("Hoje: ",hoje)
amanha  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Amanhã: ",amanha)

Ontem:  2018-09-08
Hoje:  2018-09-09
Amanhã:  2018-09-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
y = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(y)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [48]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [53]:
y = np.random.uniform(0,10,10)
print (y - y%1,"\n")
print (np.floor(y),"\n")
print (np.ceil(y)-1,"\n")
print (y.astype(int),"\n")
print (np.trunc(y))

[4. 3. 3. 6. 5. 2. 9. 6. 5. 5.] 

[4. 3. 3. 6. 5. 2. 9. 6. 5. 5.] 

[4. 3. 3. 6. 5. 2. 9. 6. 5. 5.] 

[4 3 3 6 5 2 9 6 5 5] 

[4. 3. 3. 6. 5. 2. 9. 6. 5. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [55]:
y = np.zeros((5,5))
y += np.arange(5)
print(y)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [59]:
def  gerador():
    for x in range(10):
        yield x
y = np.fromiter(gerador(),dtype=float,count=-1)
y

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [58]:
y = np.linspace(0,1,11,endpoint=False)[1:]
y

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [60]:
y = np.random.random(10)
print(y)
y.sort()
y

[0.44249092 0.75625297 0.19277238 0.98988714 0.72170575 0.09994193
 0.43241326 0.04520988 0.73125357 0.4469246 ]


array([0.04520988, 0.09994193, 0.19277238, 0.43241326, 0.44249092,
       0.4469246 , 0.72170575, 0.73125357, 0.75625297, 0.98988714])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [63]:
y = np.arange(10)
soma = np.add.reduce(y)
soma

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [64]:
x = np.random.randint(0,2,5)
y = np.random.randint(0,2,5)
z = np.array_equal(x,y)
print(z)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [3]:
y = np.zeros(10)
y.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [69]:
y = np.random.random((10,2))
a,b = y[:,0], y[:,1]
r = np.sqrt(a**2+b**2)
t = np.arctan2(b,a)
print(r)
print(t)

[0.2546371  0.96210523 0.61997056 1.07630926 0.21569527 0.8571478
 0.04643696 0.91365145 1.34204413 0.27975453]
[1.54948465 1.23753544 0.64060233 0.43430398 0.14014648 0.73576304
 1.08787425 0.33431678 0.7720372  1.06281317]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [71]:
y = np.random.random(10)
y[y.argmax()] = 0
y

array([0.69622772, 0.09778497, 0.84318048, 0.54886487, 0.        ,
       0.8755035 , 0.52463136, 0.4417246 , 0.12930705, 0.58503848])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [73]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [4]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
np.linalg.det(c)

3638.1636371179666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [7]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    print("\n")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    print("\n")

-128
127


-2147483648
2147483647


-9223372036854775808
9223372036854775807


-3.4028235e+38
3.4028235e+38
1.1920929e-07


-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16




#### 49. How to print all the values of an array? (★★☆)

In [8]:
np.set_printoptions(threshold=np.nan)
y = np.zeros((16,16))
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [9]:
y = np.arange(100)
x = np.random.uniform(0,100)
index = (np.abs(y-x)).argmin()
y[index]

38

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [11]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [13]:
y = np.random.random((10,2))
X,Y = np.atleast_2d(y[:,0], y[:,1])
d = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(d)

import scipy.spatial

y = np.random.random((10,2))
d = scipy.spatial.distance.cdist(y,y)
print(d)

[[0.         0.81610176 0.74342264 0.71695114 0.70112659 0.59747738
  0.30045252 0.74212536 0.20896117 0.88148906]
 [0.81610176 0.         0.98679763 0.22113721 0.84406786 0.35779812
  0.97707975 0.63712063 0.84494592 0.2944936 ]
 [0.74342264 0.98679763 0.         0.76887935 0.14767008 0.6320682
  0.52848741 0.38919494 0.54115504 0.80746563]
 [0.71695114 0.22113721 0.76887935 0.         0.62470929 0.15429419
  0.81963502 0.41670529 0.69607295 0.17669733]
 [0.70112659 0.84406786 0.14767008 0.62470929 0.         0.49285489
  0.54147866 0.24319905 0.51647267 0.65984329]
 [0.59747738 0.35779812 0.6320682  0.15429419 0.49285489 0.
  0.67092178 0.31821531 0.55165894 0.28829872]
 [0.30045252 0.97707975 0.52848741 0.81963502 0.54147866 0.67092178
  0.         0.67735859 0.13594461 0.95271842]
 [0.74212536 0.63712063 0.38919494 0.41670529 0.24319905 0.31821531
  0.67735859 0.         0.60548111 0.42170958]
 [0.20896117 0.84494592 0.54115504 0.69607295 0.51647267 0.55165894
  0.13594461 0.605481

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [14]:
y = np.arange(10, dtype=np.float32)
y = y.astype(np.int32, copy=False)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [15]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
y = np.genfromtxt(s, delimiter=",", dtype=np.int)
y

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [16]:
y = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(y):
    print(index, value)
for index in np.ndindex(y.shape):
    print(index, y[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [17]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [18]:
n = 10
p = 3
y = np.zeros((n,n))
np.put(y, np.random.choice(range(n*n), p, replace=False),1)
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [19]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y

array([[ 0.34944402, -0.14006184,  0.16503036, -0.33109437, -0.19787454,
         0.06519024,  0.35567707, -0.14952959,  0.15976483, -0.27654618],
       [-0.43935146, -0.22799368,  0.32105136,  0.45761157, -0.06502348,
        -0.06330617,  0.32588635, -0.41884928, -0.32049316,  0.43046797],
       [-0.29018444,  0.15747875, -0.28869229,  0.12640593,  0.19964345,
         0.34842581, -0.2784386 ,  0.30464809, -0.35292258,  0.07363587],
       [-0.24563158, -0.46540665,  0.03859988,  0.37603518, -0.3203326 ,
        -0.22146892,  0.51183208,  0.16788457, -0.11947318,  0.27796123],
       [-0.03413789,  0.19443072, -0.21557487,  0.05508241, -0.12588887,
        -0.39246244, -0.00498385,  0.39967739,  0.03575076,  0.08810664]])

#### 59. How to sort an array by the nth column? (★★☆)

In [20]:
y = np.random.randint(0,10,(3,3))
print(y)
print(y[y[:,1].argsort()])

[[9 7 0]
 [6 8 8]
 [7 3 1]]
[[7 3 1]
 [9 7 0]
 [6 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [22]:
y = np.random.randint(0,3,(3,10))
print((~y.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [23]:
y = np.random.uniform(0,1,10)
x = 0.5
m = y.flat[np.abs(y - x).argmin()]
m

0.4175002720368589

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [25]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)